Trello task: https://trello.com/c/QSsPR3Qp
xrnl/extinction-rebellion-nl pull request #138
Opened 2021-04-14 20:08 UTC by berry

Added custom field structure. Structure is a list of circle titles, descriptions and a link to the wiki. Also created structure_circles.php. I added a screenshot of how the /structuur page looks in development.

![Screenshot_2021-04-14 Structuur · Extinction Rebellion Nederland](https://user-images.githubusercontent.com/1213/114772257-e261fa00-9d6d-11eb-9ec9-b27d032ebdb5.png)

When deployed in production, the /structuur page needs to point to the template structure_circles. Then the content for the organisational structure can be added.

And then the second part of the Trello task can be completed: making references to the organisational structure elements.

Please review this pull request.

2021-05-01 08:33 UTC, SamLubbers requested changes
@berry thank you so much for making these changes and sorry it took so long to review it :pray: 

The page looks exactly like we had envisioned when creating the task :star_struck: With the custom fields you created now it's very easy to add information about the working groups.

I'll first share some feedback on the design and then some feedback on the code.

### Design feedback

- [ ] The wiki button would look better if the colour is black, so it's consistent with the colour of other buttons on the website and because black compliments better with yellow.

Looking at the current design, there are a couple of things that could make the page even better (but which weren't described at first in the Trello task)

- [ ] Instead of just having one button for the wiki, it would be useful if working circles can add any number of buttons. That way they could link to their Mattermost channel, to a document explaining how to join that group...  For an example of how this can be done, see the template `web/app/themes/xrnl/doe-mee.php:72`, and the custom field group that is used with that templte `join page sections`
- [ ] It would be good if there is a title before the description of working groups. This title should use the `font-xr` class that other titles have, and it should be a new custom field, so that people can change the text of the title from within wordpress. And of course, the title should also have a `href=#working-groups` so that other pages can link to it.

### Code feedback

- [ ] In the custom fields it's useful to add `placeholder` text so that groups know what kind of information is expected.
    - In the `title` field, I would set the placeholder: `Title of the working group: Outreach & Training, Tech...`
    - In the `description` field I would set a placeholder of `Some information about the working group`
    - In the `link` field, in addition to having a placeholder for each of the (new) fields, I would also add a small description to the field `Here you can add any number of buttons to show up on the website`
- [ ] In the code I left one comment about improving the link to each individual group
- [ ] The location of the custom field group you've created is currently configured to `Show this field group if page = structuur`. While this works, what is even better is to link a custom field group to a template, because it's the template that reads the values from the custom fields. 

![image](https://user-images.githubusercontent.com/15846595/116775570-e8412600-aa63-11eb-9625-4b986a8eb2c1.png)


### Other comments

- At the end of your pull request you mentioned: 

> When deployed in production, the /structuur page needs to point to the
> template structure_circles. Then the content for the organisational structure
> can be added.

If there are things that need to be done after deployment it's best to add them to the Trello task. That way we can easily keep track of everything that still needs to be done. I've added it already to this task so that you can see an example

- In the future it's useful if you give the pull request a descriptive title.  For example, in this case it might be "Working circles on structure page".  That way we can easily find this code back in the future. It's really good if you still link the Trello task in the descritption

Thanks again for making these changes :green_heart: And let me know when you'd like me to do the final review :v:

2021-05-01 08:33 UTC, SamLubbers commented on web/app/themes/xrnl/structure_circles.php
> +          $groupId = "circle-" . get_row_index();
For the `href` of each working group, it's better to use the name of the group for 2 reasons:

1. If the order of the circles changes, the link to the groups will also change, and old links will not point to the right circle anymore
2. It's harder to remember

In the Trello task I shared some tips on how you could achieve this

If the field containing the name of the local group name is `$group`, and the subfield for the group name is `$name` then you could do the following to insert the name of the group in the `href` field. `href="<?php echo $group->name; ?>"`

the only thing to add to this code is replacing the spaces in the group name with underscores. So `Media & Communications` would become `Media_&_communications`. Another option is to only use the first word, so that the links are simpler. So `Media & Communications` would become `media`, which could then be accessed via `/structure/#media`

2021-05-23 14:51 UTC, berry reviewed
I have processed all the comments on the pull request. Please review the update on this pull request. Thank you very much in advance.

[Structuur · Extinction Rebellion Nederland.pdf](https://github.com/xrnl/extinction-rebellion-nl/files/6528268/Structuur.Extinction.Rebellion.Nederland.pdf)

2021-05-23 14:51 UTC, berry commented on web/app/themes/xrnl/structure_circles.php
> +          $groupId = "circle-" . get_row_index();
Changed the code to `$groupId = "circle-" . formatElementID(get_sub_field('title'));`. This code works. I tried leaving out `circle-` but then the collapsing does not work. Leaving out the `"circle-" .` does also result in the collapsing of the group items not working. I do not understand PHP well enough (not yet at least) to understand why.

2021-05-30 18:00 UTC, SamLubbers commented on web/app/themes/xrnl/structure_circles.php
> +          $groupId = "circle-" . get_row_index();
@berry I figured out what is wrong here! When you remove the `"circle-"` part then there are two html elements with the same id (see both elements that use `formatElementID`). Because of this, when you click on the button a second time, it doesn't only hide the description, but the div containg also the button. Keeping it like this works fine. If you want to make it even more descriptive you can make the second id `$groupId = formatElementID(get_sub_field('title')) . "-description";`

2021-05-30 18:07 UTC, SamLubbers requested changes
@berry thank you for implementing all the suggestions :green_heart: It works great :sunglasses: There are only a couple of small suggestions that I made which can be fixed in a few minutes. 

This is almost going live!! :grin: :rocket:

2021-05-30 18:08 UTC, SamLubbers commented on web/app/themes/xrnl/structure_circles.php
> +    return strtolower(str_replace(array(' ', ' & '), '-', $str));
Oh and since this function is used in multiple places, could you also fix it there? Or maybe even better, have a single version of this function in `functions.php`

2021-05-30 20:53 UTC, berry commented on web/app/themes/xrnl/structure_circles.php
> +            <h1 class="font-xr" href="#working-groups"><?php the_field('title') ?></h1>
Fixed. I should have noticed that mistake. 😄

2021-05-30 21:55 UTC, berry reviewed
Moved formatElementID to functions.php. Extended the function to also include ', '. Because that character combination was used on the about-page. Made sure that all formatElementID functions used on other pages are removed. Tested all pages where formatElementID was used. And also fixed the id-attribute error on the structure-circles page.

2021-05-31 08:24 UTC, SamLubbers approved these changes

2021-05-31 08:25 UTC, merged